Add support for lists in versions
Harry-Lees/pre-commit-pin-dependencies pull request #6
Opened 2024-10-14 16:06 UTC by tonyay163

Poetry supports lists in versions, my usecase is for picking different version of torch in linux vs macos. Added support for it with some extra tests

2024-10-22 07:43 UTC, Harry-Lees commented
This PR doesn't pass the tests on my machine

```
=========================================================================================================================================================================== test session starts ============================================================================================================================================================================
platform darwin -- Python 3.10.13, pytest-7.2.1, pluggy-1.0.0 -- /Users/harrylees/Documents/GitHub/pre-commit-pin-dependencies/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/harrylees/Documents/GitHub/pre-commit-pin-dependencies
collected 9 items

tests/iter_dependencies_test.py::test_iter_dependencies FAILED                                                                                                                                                                                                                                                                                                       [ 11%]
tests/iter_dependencies_test.py::test_iter_dependencies_no_dependencies PASSED                                                                                                                                                                                                                                                                                       [ 22%]
tests/iter_dependencies_test.py::test_iter_dependencies_unexpected_version_type PASSED                                                                                                                                                                                                                                                                               [ 33%]
tests/pin_dependency_test.py::test_no_dependencies PASSED                                                                                                                                                                                                                                                                                                            [ 44%]
tests/pin_dependency_test.py::test_pinned_dependencies PASSED                                                                                                                                                                                                                                                                                                        [ 55%]
tests/pin_dependency_test.py::test_unpinned_dependencies[tests/resources/caret.toml] PASSED                                                                                                                                                                                                                                                                          [ 66%]
tests/pin_dependency_test.py::test_unpinned_dependencies[tests/resources/tilde.toml] PASSED                                                                                                                                                                                                                                                                          [ 77%]
tests/pin_dependency_test.py::test_unpinned_dependencies[tests/resources/less_than_equal.toml] PASSED                                                                                                                                                                                                                                                                [ 88%]
tests/pin_dependency_test.py::test_unpinned_dependencies[tests/resources/more_than_equal.toml] PASSED                                                                                                                                                                                                                                                                [100%]

================================================================================================================================================================================= FAILURES =================================================================================================================================================================================
__________________________________________________________________________________________________________________________________________________________________________ test_iter_dependencies __________________________________________________________________________________________________________________________________________________________________________

    def test_iter_dependencies() -> None:
        dependencies = iter_dependencies({
            "tool": {
                "poetry": {
                    "dependencies": {
                        "requests": "^2.25.1",
                        "toml": {"version": "^0.10.2"},
                        "torch": [
                            {"version": "^2.2.2"},
                            {"version": "^2.2.2+cpu"},
                        ],
                    }
                }
            }
        })
>       assert list(dependencies) == [
            ("requests", "^2.25.1"),
            ("toml", "^0.10.2"),
        ]
E       AssertionError: assert [('requests', '^2.25.1'), ('toml', '^0.10.2'), ('torch', '^2.2.2'), ('torch', '^2.2.2+cpu')] == [('requests', '^2.25.1'), ('toml', '^0.10.2')]
E         Left contains 2 more items, first extra item: ('torch', '^2.2.2')
E         Full diff:
E           [
E            ('requests',
E             '^2.25.1'),
E            ('toml',
E             '^0.10.2'),
E         +  ('torch',
E         +   '^2.2.2'),
E         +  ('torch',
E         +   '^2.2.2+cpu'),
E           ]

tests/iter_dependencies_test.py:21: AssertionError
```

2024-10-22 07:46 UTC, Harry-Lees requested changes
Please fix the tests before we merge this.

2024-10-22 16:31 UTC, tonyay163 commented
ah whoops, I was splitting up the PR and made a mistake. I've updated !

2024-10-23 17:58 UTC, Harry-Lees approved these changes

2024-10-23 17:58 UTC, merged